title: Opnamestudio in Vlaams brabant België
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.7680851
favicon: null
name: opname-studio.be
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6995584978722036
  saturation: 0.25
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.9375
  rhythmicContrast: 0
typography_spectrum: 0.8573895168956369
