name: opname-studio.be
favicon: null
layout_spectrum: 0.757902140263468
typography_spectrum: 0.8573895168956369
title: Opnamestudio in Vlaams brabant België
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6995584978722036
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
